### ISSUE TITLE
Feature: Pretty permalinks activated after installation

### ISSUE THREAD

**Issue by daniel-marklund** [jumpstarter-io/wp-jumpstarter#4]
From WordPress Codex (http://codex.wordpress.org/Using_Permalinks)

```
Default "Ugly": http://example.com/?p=N
...
Post name: http://example.com/sample-post/
```

Unfortunately the ugly permalinks are default in WordPress for unknown reasons. I would like an easy way to set the post name as a standard permalink structure in Jumpstarter for my WordPress app.

In order to succeed with this, the nginx configuration needs to be changed to:

```
location / {
    try_files $uri $uri/ /index.php?$args; 
 }
```

But, that is not enough. You also need to change the `wp_options (DB-table)` variable `permalink_structure` to /%postname%.

It would be great if this could be set in the extra env for my app.

**Comment by hnsl** [comment]
Fixed in 6.0.
